---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r echo = TRUE, message = FALSE}
library("dplyr")
library("lubridate")
activity <- read.csv(unz("activity.zip", "activity.csv")) %>% 
    tbl_df %>% 
    mutate(date = ymd(date))
``` 


## What is mean total number of steps taken per day?
```{r echo = FALSE, message = FALSE}
library("ggplot2")
totalStepsPerDay <- activity %>% group_by(date) %>% summarise(total = sum(steps))
ggplot(totalStepsPerDay, aes(total)) + geom_histogram() + xlab("Total number of steps taken each day")
``` 

Mean:
```{r echo = TRUE}
mean(totalStepsPerDay$total, na.rm = TRUE)
```

Median:
```{r echo = TRUE}
median(totalStepsPerDay$total, na.rm = TRUE)
```


## What is the average daily activity pattern?
```{r echo = TRUE}
meanStepsPerInterval <- activity %>% group_by(interval) %>% summarise(average = mean(steps, na.rm = TRUE)) 
with(meanStepsPerInterval, plot(interval, average, type = "l", xlab = "5 minutes interval", ylab = "Average number of steps", lwd = 2))
```

Interval containing maximum number of steps:
```{r echo = TRUE}
(meanStepsPerInterval %>% filter(average == max(meanStepsPerInterval$average)))$interval
```



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
